---
- name: setup build
  hosts: build
  become: yes

  tasks:
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: git clone repository
    git:
      repo: "https://github.com/boxfuse/boxfuse-sample-java-war-hello.git"
      dest: "/root/project"
      version: master

  - name: Build project by maven
    shell: cd /root/project && mvn -B package

  - name: Copy war to tomcat server
    synchronize:
      src: /root/project/target/hello-1.0.war
      dest: "/tmp"
      mode: pull
    delegate_to: tomcat1



- name: setup tomcat
  hosts: tomcat
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started

  - name: Copy war from tmp
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps
      remote_src: true